/*
 * CiberLoja API
 * API para gestionar tienda 
 *
 * OpenAPI spec version: 1.0
 * Contact: soporte@reflevision.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient.js';

/**
 * The Concelho model module.
 * @module model/Concelho
 * @version 1.0
 */
export default class Concelho {
  /**
   * Constructs a new <code>Concelho</code>.
   * @alias module:model/Concelho
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Concelho</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Concelho} obj Optional instance to populate.
   * @return {module:model/Concelho} The populated <code>Concelho</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Concelho();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('nombre'))
        obj.nombre = ApiClient.convertToType(data['nombre'], 'String');
      if (data.hasOwnProperty('distritoId'))
        obj.distritoId = ApiClient.convertToType(data['distritoId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Concelho.prototype.id = undefined;

/**
 * @member {String} nombre
 */
Concelho.prototype.nombre = undefined;

/**
 * @member {Number} distritoId
 */
Concelho.prototype.distritoId = undefined;

