/*
 * CiberLoja API
 * API para gestionar tienda 
 *
 * OpenAPI spec version: 1.0
 * Contact: soporte@reflevision.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient.js';

/**
 * The Freguesia model module.
 * @module model/Freguesia
 * @version 1.0
 */
export default class Freguesia {
  /**
   * Constructs a new <code>Freguesia</code>.
   * @alias module:model/Freguesia
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Freguesia</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Freguesia} obj Optional instance to populate.
   * @return {module:model/Freguesia} The populated <code>Freguesia</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Freguesia();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('nombre'))
        obj.nombre = ApiClient.convertToType(data['nombre'], 'String');
      if (data.hasOwnProperty('concelhoId'))
        obj.concelhoId = ApiClient.convertToType(data['concelhoId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Freguesia.prototype.id = undefined;

/**
 * @member {String} nombre
 */
Freguesia.prototype.nombre = undefined;

/**
 * @member {Number} concelhoId
 */
Freguesia.prototype.concelhoId = undefined;

